/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lenguajesproyecto.FrontEnd.PromptZal_FrontEnd_Swimng;

import java.net.URL;

import javax.swing.ImageIcon;

/**
 *
 * @author ricardocastillo
 */
public class MenuInicialSegundo extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(MenuInicialSegundo.class.getName());

    /**
     * Creates new form MenuInicialSegundo
     */
    public MenuInicialSegundo() {
        initComponents();

        try {

            URL iconURL = getClass().getResource("/com/ricardo/Logo/LogoApp.jpg");
            if (iconURL != null) {
                this.setIconImage(new ImageIcon(iconURL).getImage());
            } else {
                System.err.println("Advertencia: No se encontró el archivo de logo en la ruta especificada.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar2 = new javax.swing.JToolBar();
        JbAbrir = new javax.swing.JButton();
        JbEjecutar = new javax.swing.JButton();
        JbExportar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        JlDeEstados = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        JlNombreArchivo = new javax.swing.JLabel();
        JsEditor = new javax.swing.JScrollPane();
        JtextAreaDeEditor = new javax.swing.JTextArea();
        jSplitPane2 = new javax.swing.JSplitPane();
        JpTokens = new javax.swing.JPanel();
        TituloTokenTabla = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar2.setRollover(true);

        JbAbrir.setText("Open .pz File");
        JbAbrir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JbAbrir.setFocusable(false);
        JbAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JbAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JbAbrir.addActionListener(this::JbAbrirActionPerformed);
        jToolBar2.add(JbAbrir);

        JbEjecutar.setText("Run Lexical Analysis");
        JbEjecutar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JbEjecutar.setFocusable(false);
        JbEjecutar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JbEjecutar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JbEjecutar.addActionListener(this::JbEjecutarActionPerformed);
        jToolBar2.add(JbEjecutar);

        JbExportar.setText("Export HTML Reports");
        JbExportar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JbExportar.setFocusable(false);
        JbExportar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JbExportar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JbExportar.addActionListener(this::JbExportarActionPerformed);
        jToolBar2.add(JbExportar);

        getContentPane().add(jToolBar2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        JlDeEstados.setText("Status: Ready. | File: none | Total Tokens: 0 | Errors: 0");
        jPanel1.add(JlDeEstados, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setResizeWeight(0.5);

        jPanel2.setLayout(new java.awt.BorderLayout());

        JlNombreArchivo.setText("Source Code Editor (.pz)");
        jPanel2.add(JlNombreArchivo, java.awt.BorderLayout.PAGE_START);

        JtextAreaDeEditor.setColumns(20);
        JtextAreaDeEditor.setRows(5);
        JsEditor.setViewportView(JtextAreaDeEditor);

        jPanel2.add(JsEditor, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(jPanel2);

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane2.setResizeWeight(0.5);

        JpTokens.setLayout(new java.awt.BorderLayout());

        TituloTokenTabla.setText("Token Table Output");
        JpTokens.add(TituloTokenTabla, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.", "Lexema", "Tipo", "Fila", "Columna"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        JpTokens.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane2.setTopComponent(JpTokens);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Lexical Error Report");
        jPanel3.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.", "Error", "Descripcion", "Fila", "Columna"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jSplitPane2.setRightComponent(jPanel3);

        jSplitPane1.setRightComponent(jSplitPane2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbAbrirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_JbAbrirActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_JbAbrirActionPerformed

    private void JbEjecutarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_JbEjecutarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_JbEjecutarActionPerformed

    private void JbExportarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_JbExportarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_JbExportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuInicialSegundo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbAbrir;
    private javax.swing.JButton JbEjecutar;
    private javax.swing.JButton JbExportar;
    private javax.swing.JLabel JlDeEstados;
    private javax.swing.JLabel JlNombreArchivo;
    private javax.swing.JPanel JpTokens;
    private javax.swing.JScrollPane JsEditor;
    private javax.swing.JTextArea JtextAreaDeEditor;
    private javax.swing.JLabel TituloTokenTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
