/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lenguajesproyecto.FrontEnd.PromptZal_FrontEnd_Swimng;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

import com.mycompany.lenguajesproyecto.BackEnd.PromptZal_BacKEnd_Proyecto.BibliotecaCarpeta.BibliotecaDeDot;
import com.mycompany.lenguajesproyecto.BackEnd.PromptZal_BacKEnd_Proyecto.InicioCarpeta.AnailizadorDeTexto;
import com.mycompany.lenguajesproyecto.BackEnd.PromptZal_BacKEnd_Proyecto.ReportesCarpeta.ReporteDeError;
import com.mycompany.lenguajesproyecto.BackEnd.PromptZal_BacKEnd_Proyecto.ReportesCarpeta.ReporteHTMLTabla;
import com.mycompany.lenguajesproyecto.BackEnd.PromptZal_BacKEnd_Proyecto.ReportesCarpeta.ReportesHtml;
import com.mycompany.lenguajesproyecto.FrontEnd.PromptZal_FrontEnd.Configuraciones;
import com.mycompany.lenguajesproyecto.FrontEnd.PromptZal_FrontEnd_Swimng.OpcionesDeVisualizacion.TextLineNumber;

/**
 *
 * @author ricardocastillo
 */
@SuppressWarnings("rawtypes")
public class MenuInicialSegundo extends javax.swing.JFrame {
    private int contadorDeAlalizaciones;
    private String nombreArchivo;
    private ReporteDeError reporteErroresHtml;
    private ReporteHTMLTabla reporteHtml;
    private ReportesHtml guardado;
    private DefaultTableModel tablaDeErroresModelo;
    private DefaultTableModel tablaDeTokensAceptados;
    private BibliotecaDeDot dotBiblioteca;

    @SuppressWarnings("unused")

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(MenuInicialSegundo.class.getName());

    /**
     * Creates new form MenuInicialSegundo
     */
    public MenuInicialSegundo() {
        initComponents();
        guardado = new ReportesHtml();
        tablaDeErroresModelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaDeTokensAceptados = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        reiniciadorDeTablas();
        contadorDeAlalizaciones = 0;
        TextLineNumber number = new TextLineNumber(JtextAreaDeEditor);
        JsEditor.setRowHeaderView(number);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar2 = new javax.swing.JToolBar();
        JbAbrir = new javax.swing.JButton();
        JbEjecutar = new javax.swing.JButton();
        JbExportar = new javax.swing.JButton();
        JbImagenADF = new javax.swing.JButton();
        GuaradrArchivoPz = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        JlDeEstados = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        JlNombreArchivo = new javax.swing.JLabel();
        JsEditor = new javax.swing.JScrollPane();
        JtextAreaDeEditor = new javax.swing.JTextArea();
        jSplitPane2 = new javax.swing.JSplitPane();
        JpTokens = new javax.swing.JPanel();
        TituloTokenTabla = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTablaDeTokens = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTablaErrores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar2.setBackground(new java.awt.Color(30, 30, 30));
        jToolBar2.setBorder(null);
        jToolBar2.setRollover(true);

        JbAbrir.setBackground(new java.awt.Color(70, 70, 70));
        JbAbrir.setForeground(new java.awt.Color(31, 138, 210));
        JbAbrir.setText("Abrir .pz Archivo");
        JbAbrir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JbAbrir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JbAbrir.setFocusable(false);
        JbAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JbAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JbAbrir.addActionListener(this::JbAbrirActionPerformed);
        jToolBar2.add(JbAbrir);

        JbEjecutar.setBackground(new java.awt.Color(70, 70, 70));
        JbEjecutar.setForeground(new java.awt.Color(31, 138, 210));
        JbEjecutar.setText("Correr analizador");
        JbEjecutar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JbEjecutar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JbEjecutar.setFocusable(false);
        JbEjecutar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JbEjecutar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JbEjecutar.addActionListener(this::JbEjecutarActionPerformed);
        jToolBar2.add(JbEjecutar);

        JbExportar.setBackground(new java.awt.Color(70, 70, 70));
        JbExportar.setForeground(new java.awt.Color(31, 138, 210));
        JbExportar.setText("Exportar HTML Reports");
        JbExportar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JbExportar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JbExportar.setFocusable(false);
        JbExportar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JbExportar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JbExportar.addActionListener(this::JbExportarActionPerformed);
        jToolBar2.add(JbExportar);

        JbImagenADF.setBackground(new java.awt.Color(70, 70, 70));
        JbImagenADF.setForeground(new java.awt.Color(31, 138, 210));
        JbImagenADF.setText("Imagen (AFD)");
        JbImagenADF.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JbImagenADF.setFocusable(false);
        JbImagenADF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JbImagenADF.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JbImagenADF.addActionListener(this::JbImagenADFActionPerformed);
        jToolBar2.add(JbImagenADF);

        GuaradrArchivoPz.setBackground(new java.awt.Color(70, 70, 70));
        GuaradrArchivoPz.setForeground(new java.awt.Color(31, 138, 210));
        GuaradrArchivoPz.setText("Guardar .pz");
        GuaradrArchivoPz.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GuaradrArchivoPz.setFocusable(false);
        GuaradrArchivoPz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GuaradrArchivoPz.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        GuaradrArchivoPz.addActionListener(this::GuaradrArchivoPzActionPerformed);
        jToolBar2.add(GuaradrArchivoPz);

        getContentPane().add(jToolBar2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(30, 30, 30));
        jPanel1.setLayout(new java.awt.BorderLayout());

        JlDeEstados.setForeground(new java.awt.Color(212, 212, 212));
        JlDeEstados.setText("Status: Ready. | File: none | Total Tokens: 0 | Errors: 0");
        jPanel1.add(JlDeEstados, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jSplitPane1.setBackground(new java.awt.Color(30, 30, 30));
        jSplitPane1.setDividerLocation(300);
        jSplitPane1.setResizeWeight(0.5);
        jSplitPane1.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(45, 45, 45));
        jPanel2.setLayout(new java.awt.BorderLayout());

        JlNombreArchivo.setForeground(new java.awt.Color(212, 212, 212));
        JlNombreArchivo.setText("Source Code Editor (.pz)");
        jPanel2.add(JlNombreArchivo, java.awt.BorderLayout.PAGE_START);

        JtextAreaDeEditor.setBackground(new java.awt.Color(45, 45, 45));
        JtextAreaDeEditor.setColumns(20);
        JtextAreaDeEditor.setRows(5);
        JsEditor.setViewportView(JtextAreaDeEditor);

        jPanel2.add(JsEditor, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(jPanel2);

        jSplitPane2.setBackground(new java.awt.Color(45, 45, 45));
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane2.setResizeWeight(0.5);

        JpTokens.setBackground(new java.awt.Color(45, 45, 45));
        JpTokens.setLayout(new java.awt.BorderLayout());

        TituloTokenTabla.setBackground(new java.awt.Color(255, 255, 255));
        TituloTokenTabla.setForeground(new java.awt.Color(212, 212, 212));
        TituloTokenTabla.setText("Token Table Output");
        JpTokens.add(TituloTokenTabla, java.awt.BorderLayout.PAGE_START);

        JTablaDeTokens.setBackground(new java.awt.Color(45, 45, 45));
        JTablaDeTokens.setForeground(new java.awt.Color(212, 212, 212));
        JTablaDeTokens.getTableHeader().setBackground(new java.awt.Color(30, 30, 30));
        JTablaDeTokens.getTableHeader().setForeground(new java.awt.Color(212, 212, 212));
        JTablaDeTokens.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null }
                },
                new String[] {
                        "No.", "Lexema", "Tipo", "Fila", "Columna"
                }) {
            Class[] types = new Class[] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class
            };
            boolean[] canEdit = new boolean[] {
                    false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        JTablaDeTokens.setGridColor(new java.awt.Color(133, 133, 133));
        jScrollPane1.setViewportView(JTablaDeTokens);

        JpTokens.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane2.setTopComponent(JpTokens);

        jPanel3.setBackground(new java.awt.Color(45, 45, 45));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setForeground(new java.awt.Color(212, 212, 212));
        jLabel1.setText("Lexical Error Report");
        jPanel3.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane2.setBackground(new java.awt.Color(212, 212, 212));

        JTablaErrores.setBackground(new java.awt.Color(45, 45, 45));
        JTablaErrores.setForeground(new java.awt.Color(212, 212, 212));
        JTablaErrores.getTableHeader().setBackground(new java.awt.Color(30, 30, 30));
        JTablaErrores.getTableHeader().setForeground(new java.awt.Color(212, 212, 212));
        JTablaErrores.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null }
                },
                new String[] {
                        "No.", "Error", "Descripcion", "Fila", "Columna"
                }) {
            Class[] types = new Class[] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class
            };
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        JTablaErrores.setGridColor(new java.awt.Color(133, 133, 133));
        jScrollPane2.setViewportView(JTablaErrores);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jSplitPane2.setRightComponent(jPanel3);

        jSplitPane1.setRightComponent(jSplitPane2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuaradrArchivoPzActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_GuaradrArchivoPzActionPerformed
        JFileChooser fileChooser = new JFileChooser();

        fileChooser.setFileFilter(new FileNameExtensionFilter("Archivos PromptZal (*.pz)", "pz"));

        int resultado = fileChooser.showSaveDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            String rutaArchivo = archivo.getAbsolutePath();
            if (!rutaArchivo.endsWith(".pz")) {
                archivo = new File(rutaArchivo + ".pz");
            }

            try (FileWriter fileWriter = new FileWriter(archivo); PrintWriter writer = new PrintWriter(fileWriter)) {
                writer.print(JtextAreaDeEditor.getText());
                Configuraciones.mensajeSi("Guardado", "Archivo guardado exitosamente en: " + archivo.getAbsolutePath());
            } catch (IOException e) {
                Configuraciones.pantallaDeError("Error Guardado", "Error al intentar guardar el archivo.");
                e.printStackTrace();
            }
        }
    }// GEN-LAST:event_GuaradrArchivoPzActionPerformed

    private void JbImagenADFActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_JbImagenADFActionPerformed
        if (dotBiblioteca != null) {

            if (guardado != null) {

                JFileChooser fileChooserParaGraphviz = new JFileChooser();
                fileChooserParaGraphviz.setFileFilter(new FileNameExtensionFilter("Archivos dot (*.dot)", "dot"));
                int resultado = fileChooserParaGraphviz.showSaveDialog(this);

                if (resultado == JFileChooser.APPROVE_OPTION) {
                    File archivo = fileChooserParaGraphviz.getSelectedFile();
                    String rutaArchivo = archivo.getAbsolutePath();

                    if (!rutaArchivo.toLowerCase().endsWith(".dot")) {
                        rutaArchivo += ".dot";
                    }

                    guardado.creadorDeArchivos(rutaArchivo, dotBiblioteca.obtenerCodigoDot());

                    Configuraciones.mensajeSi("Guardado", "Se guardó el archivo .dot exitosamente en:\n" + rutaArchivo);

                    boolean imagenCreada = dotBiblioteca.generarJpgDesdeDot(rutaArchivo);
                    if (imagenCreada) {
                    Configuraciones.mensajeSi("Imagen", "Se pudo crear la imagen");

                    } else {
                        Configuraciones.pantallaDeError("Imagen", "no se a podido crear la imagen.");
                    }
                    ImagenDeAFD image = new ImagenDeAFD(this, true, dotBiblioteca, rutaArchivo);
                    image.setVisible(true);
                }

            } else {
                Configuraciones.pantallaDeError("No se ha analizado", "Por favor analice un archivo primero.");
            }
        } else {
            Configuraciones.pantallaDeError("No se ha analizado", "Por favor analice un archivo primero.");
        }

    }// GEN-LAST:event_JbImagenADFActionPerformed

    private void JbAbrirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_JbAbrirActionPerformed
        JFileChooser selectorDeArchivosFc = new JFileChooser();
        selectorDeArchivosFc.setFileSelectionMode(JFileChooser.FILES_ONLY);

        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo de prontZalt", "pz");
        selectorDeArchivosFc.setFileFilter(filtro);

        int resultado = selectorDeArchivosFc.showOpenDialog(this);
        if (resultado != JFileChooser.CANCEL_OPTION) {
            File archivo = selectorDeArchivosFc.getSelectedFile();
            if (archivo == null || archivo.getName().equals("")) {
                JOptionPane.showMessageDialog(this, "Error al cargar el acrchivo");
            } else {
                nombreArchivo = archivo.getName();
                JlNombreArchivo.setText(archivo.getName());
                escritorDePz(archivo.getAbsolutePath());
            }
        }

    }// GEN-LAST:event_JbAbrirActionPerformed

    private void JbEjecutarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_JbEjecutarActionPerformed
        contadorDeAlalizaciones++;
        AnailizadorDeTexto anailizadorDeTexto = new AnailizadorDeTexto();
        reiniciadorDeTablas();
        try {
            anailizadorDeTexto.lector(JtextAreaDeEditor, contadorDeAlalizaciones);
            dotBiblioteca = anailizadorDeTexto.getBibliotecaDot();
            reporteHtml = anailizadorDeTexto.getReporteHTMLTabla();
            reporteErroresHtml = anailizadorDeTexto.getReportesError();
            tablaDeErroresModelo = reporteErroresHtml.tablaDeTokensConsola(tablaDeErroresModelo);
            tablaDeTokensAceptados = reporteHtml.tablaDeTokensConsola(tablaDeTokensAceptados);
            JlDeEstados.setText("Estado: Finalizado. | Archivo: " + nombreArchivo + " | Total Tokens: "
                    + reporteHtml.getTamano() + " | Errors: " + reporteErroresHtml.getTamano());

        } catch (IOException e) {
            Configuraciones.pantallaDeError("Error en el analizador", "Se obtuvo un error en la lectura");

        }
    }// GEN-LAST:event_JbEjecutarActionPerformed

    private void JbExportarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_JbExportarActionPerformed

        if (reporteErroresHtml != null && reporteHtml != null) {

            JFileChooser fileChooserParaHtml = new JFileChooser();
            fileChooserParaHtml.setFileFilter(new FileNameExtensionFilter("Archivos html (*.html)", "html"));
            int resultado = fileChooserParaHtml.showSaveDialog(this);

            if (resultado == JFileChooser.APPROVE_OPTION) {
                File archivo = fileChooserParaHtml.getSelectedFile();
                String rutaArchivo = archivo.getAbsolutePath();

                if (!rutaArchivo.toLowerCase().endsWith(".html")) {
                    rutaArchivo += ".html";
                }

                File directorioPadre = archivo.getParentFile();
                String rutaDirectorio = (directorioPadre != null) ? directorioPadre.getAbsolutePath() : "";

                StringBuilder htmlError = reporteErroresHtml.generarHTMLDeError();
                reporteErroresHtml.creadorDeArchivos(
                        rutaDirectorio + File.separator + "ReportesError_" + nombreArchivo + ".html", htmlError);

                StringBuilder html = reporteHtml.generarHTMLDeTokens();
                reporteHtml.creadorDeArchivos(
                        rutaDirectorio + File.separator + "TablaDeTokens_" + nombreArchivo + ".html", html);

                reporteErroresHtml = null;
                reporteHtml = null;

                Configuraciones.mensajeSi("Guardado exitoso",
                        "Se guardaron los reportes HTML en la ruta:\n" + rutaDirectorio);
            }

        } else {
            Configuraciones.pantallaDeError("No se ha analizado",
                    "Por favor analice un archivo primero antes de exportar.");
        }

    }// GEN-LAST:event_JbExportarActionPerformed

    private void escritorDePz(String phat) {
        File archivo = new File(phat);
        JtextAreaDeEditor.setText("");
        try (BufferedReader lectorPrincipal = new BufferedReader(new FileReader(archivo))) {
            String linea;
            while ((linea = lectorPrincipal.readLine()) != null) {
                JtextAreaDeEditor.append(linea + "\n");
            }
        } catch (IOException e) {
            Configuraciones.pantallaDeError("Error", "Error al leer el archivo: " + e.getMessage());
        }
    }

    private void reiniciadorDeTablas() {
        String[] idesToken = { "No.", "Lexema", "Tipo", "Descripcion", "Fila", "Columna" };
        String[] idesErrores = { "No.", "Error", "Descripcion", "Fila", "Columna" };
        tablaDeErroresModelo.setColumnIdentifiers(idesErrores);
        tablaDeTokensAceptados.setColumnIdentifiers(idesToken);
        JTablaDeTokens.setModel(tablaDeTokensAceptados);
        JTablaErrores.setModel(tablaDeErroresModelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GuaradrArchivoPz;
    private javax.swing.JTable JTablaDeTokens;
    private javax.swing.JTable JTablaErrores;
    private javax.swing.JButton JbAbrir;
    private javax.swing.JButton JbEjecutar;
    private javax.swing.JButton JbExportar;
    private javax.swing.JButton JbImagenADF;
    private javax.swing.JLabel JlDeEstados;
    private javax.swing.JLabel JlNombreArchivo;
    private javax.swing.JPanel JpTokens;
    private javax.swing.JScrollPane JsEditor;
    private javax.swing.JTextArea JtextAreaDeEditor;
    private javax.swing.JLabel TituloTokenTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
